### ISSUE TITLE
Add several strings to Weblate

### ISSUE THREAD

**Issue by jermanuts** [flathub-infra/website#4960]
In https://flathub.org/statistics "Category Distribution"

[Terms Of Service](https://flathub.org/ar/terms-and-conditions) page

[Privacy policy](https://flathub.org/ar/privacy-policy) page

[Consultants and Contractors](https://flathub.org/ar/consultants) page

**Comment by razzeee** [comment]
Category distribution is translatable already.

The terms and policy pages are legal stuff, which I'm unusure we can translate, without getting into trouble.

The consultants page has such a small target user audience, that it doesn't make sense to translate.

**Comment by jermanuts** [comment]
>Category distribution is translatable already.

I meant the chart's text, it is not.

Can you force other pages to be in LTR if not too complicated?

**Comment by RacerBG** [comment]
@razzeee 

![Image](https://github.com/user-attachments/assets/14bab6f9-b94c-48d5-ad84-7b2455746615)

The other pages should not be translated in my opinion as you already wrote.

**Comment by jermanuts** [comment]
@razzeee the "Next" and "Previous" navigation arrows for app's screenshots are missing too 

![Image](https://github.com/user-attachments/assets/2913a35a-3405-453f-ab8e-bca104ce0fc7)

**Comment by razzeee** [comment]
> [@razzeee](https://github.com/razzeee) the "Next" and "Previous" navigation arrows for app's screenshots are missing too
> 
> ![Image](https://github.com/user-attachments/assets/2913a35a-3405-453f-ab8e-bca104ce0fc7)

should be fixed

**Comment by jermanuts** [comment]
Aren't these are on Weblate? example `lightbox.previous`

If so, they are not changed on live website yet.

**Comment by razzeee** [comment]
Works fine on german

**Comment by jermanuts** [comment]
Yes, now translations are displayed. Category distribution/chart is still not translated and not aligned correctly for RTL languages.

**Comment by razzeee** [comment]
I'll wait for github.com/shadcn-ui/ui/pull/1638 for most of the RTL fixes, probably doesn't make much sense to fix these right now. Regarding the chart.

**Comment by jermanuts** [comment]
What about "Add-ons"? I think leaving the main name of the add-on so people can easily search for it in English and just allow its description to be translatable?

**Comment by razzeee** [comment]
Most of this should be fixed or not actionable. It's also bad, that this got to be a number of things in one ticket, which makes it hard to close. So closing now.

**Comment by jermanuts** [comment]
Oh sorry I didn't realize that the 2nd paragraph of this [comment](https://github.com/flathub-infra/website/issues/4960#issuecomment-2838140444) shouldn't have been mentioned here. I will open another issue for it.

**Comment by jermanuts** [comment]
<img width="1794" height="150" alt="Image" src="https://github.com/user-attachments/assets/b0fdabb9-0aa7-49e8-9038-e43c0991e608" />

Can you add these dates in weblate? (they are the ones in "Changes in version" card).

@razzeee

**Comment by jermanuts** [comment]
@razzeee "This application is no longer maintained." is not on weblate.

**Comment by razzeee** [comment]
That's correct and won't be changed
